///
/// @file
/// @copyright All code copyright Movidius Ltd 2014, all rights reserved.
///            For License Warranty see: common/license.txt
///
/// @brief     This file contains the source code of the SIPP pipeline
///            generated by the SIPP Graph Designer.
///
///
///  ************************ DO NOT EDIT, THIS IS A GENERATED FILE!!!! ************************
/// 

#ifndef __SIPPRGB_H__
#define __SIPPRGB_H__

#include <sipp.h>
#include <sippTestCommon.h>

#include "ISPPipeSettings.h"


//The full-frame buffers
extern UInt8 DDR_DATA SippRGB_dmaOut0_buffer[ SIPP_ISP_PIPE_BUFFER_WIDTH * SIPP_ISP_PIPE_BUFFER_HEIGHT * 3 ]ALIGNED(8);
extern UInt8 DDR_DATA SippRGB_dmaOut1_buffer[ SIPP_ISP_PIPE_BUFFER_WIDTH * SIPP_ISP_PIPE_BUFFER_HEIGHT * SIPP_ISP_PIPE_BUFFER_INPUT_NUM_PLANES ]ALIGNED(8);
	
///

typedef struct SippRGB
{
	//Filter references for human readable shape
	SippPipeline *pl;

	//Declare references to all filters in the pipeline
	SippFilter *dmaIn0;
	SippFilter *sigmaDnsMa2x5x0;
	SippFilter *lscMa2x5x0;
	SippFilter *rawMa2x5x0;
	SippFilter *debayerMa2x5x0;
	SippFilter *dmaOut0;
	SippFilter *dmaOut1;

} SippRGB;

void readSippRGBInput(SippRGB *pPl);
void writeSippRGBOutput(SippRGB *pPl);

void buildSippRGB(SippRGB *pPl);
void configSippRGB(SippRGB *pPl);


#endif