# crowd config file Only yes or no
CONFIG_SIPP_RGB=no
CONFIG_CJSON=los
CONFIG_VSC=no
CONFIG_VSC_XLINK=no
CONFIG_PLOG=los
CONFIG_ZBASE64=all
CONFIG_MICROTAR=los
CONFIG_LIBJPEG=lrt
CONFIG_EIGEN=lrt
CONFIG_ETH=los
