# crowd config file Only yes or no
CONFIG_SIPP_RGB=lrt
CONFIG_SIPP_YUV=no
CONFIG_CJSON=no
CONFIG_VSC=los
CONFIG_VSC_XLINK=no
CONFIG_PLOG=no
CONFIG_ZBASE64=no
CONFIG_LIBJPEG=no
CONFIG_EIGEN=no
CONFIG_ETH=no
